### ISSUE TITLE
would crash evry time i connect

### ISSUE THREAD

**Issue by KidWithWindows7** [BullyWiiPlaza/tcpgecko#45]
java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at java.io.DataOutputStream.flush(Unknown Source)
	at Inb.m(abh:659)
	at Inb.b(abh:577)
	at PP.W(exa:3728)
	at PP.f(exa:107)
	at tK.h(exa:4805)
	at tK.doInBackground(exa:4442)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by inklingboy7688** [comment]
Happened with me too
